Multishipping requires magento/module-braintree
Fatal error: Interface 'Magento\Multishipping\Model\Checkout\Type\Multishipping\PlaceOrderInterface' not found in /var/www/magento/vendor/magento/module-braintree/Model/Multishipping/PlaceOrder.php on line 28